# For GitLab Runner Configuration
concurrent = 5
log_level = "warning"
log_format = "json"
check_interval = 5
connection_max_age = "15m0s"
shutdown_timeout = 0    # keep existing key

[session_server]
  session_timeout = 1800

[[runners]]
  name = "gitlab-runner"
  url = "FIXME" # FIXME Change to your GitLab instance URL
  token = "FIXME" # FIXME Add your registration token here
  token_obtained_at = 2026-01-15T00:20:48Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  limit = 0
  # FIXME To increase rate limits, when pulling down images from the Docker Hub you might want to authenticate:
  # 1. Create a Docker Hub account and generate a personal access token
  # 2. Encode the username and token in base64
  #    Example: echo -n 'username:token' | base64
  # 3. Replace the <BASE64_ENCODED_AUTH> with the base64 encoded string
  # 4. Uncomment below line
  # environment = ["DOCKER_AUTH_CONFIG={\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"<BASE64_ENCODED_AUTH>\"}}}"]
  [runners.docker]
    tls_verify = false
    image = "python:3.12-slim" 
    privileged = true
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    # optional defaults you may keep or tweak
    shm_size = 0
    network_mtu = 0
  [runners.cache]
    Insecure = false